### ISSUE TITLE
Errors Scanning Final Cut Pro

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#525]
**Nash Nash says:**

```
When I try to press the "Scan Final Cut Pro" button in the preference,
I get an error message. I have attached the report and screen capture.

I hope you can fix it.

Thank You.
```

**Error Log:**

```
CommandPost v1.0.0-beta.2

macOS Version:                  10.11.6
CommandPost Locale:             en
Current Keyboard Layout:        U.S.
Final Cut Pro Path:             /Applications/Final Cut Pro.app
Final Cut Pro Version:          10.3.3
Final Cut Pro Language:         en
Developer Mode:                 false

2017-04-24 08:23:37: 2017-04-24 08:23:37: -- Loading /Users/XXX/Applications/CommandPost.app/Contents/Resources/extensions/cp/init.lua
2017-04-24 08:23:37: -- Loading extension: uielement
2017-04-24 08:23:37: -- Loading extension: window
2017-04-24 08:23:37: 08:23:37 finalcutpr:     Reloading Final Cut Pro Preferences: nil; 1492993339
2017-04-24 08:23:37:                  cp:     Loading Plugins:
2017-04-24 08:23:38: -- Done.
2017-04-24 08:24:01: ********
2017-04-24 08:24:01: 08:24:01 ERROR:    dialog: Unable to activate the Effects sidebar.

Error occurred in updateEffectsList().
2017-04-24 08:24:01: ********
2017-04-24 08:24:36: ********
2017-04-24 08:24:36: 08:24:36 ERROR: shortcuts: No Final Cut Pro Version was detected. This shouldn't happen.
2017-04-24 08:24:36: ********
2017-04-24 08:24:49: ********
2017-04-24 08:24:49: 08:24:49 ERROR: shortcuts: No Final Cut Pro Version was detected. This shouldn't happen.
2017-04-24 08:24:49: ********
2017-04-24 08:24:56: 08:24:56 finalcutpr:     Reloading Final Cut Pro Preferences: 1492993339; 1492993496
2017-04-24 08:25:46: ********
2017-04-24 08:25:46: 08:25:46 ERROR:    dialog: Unable to activate the Effects sidebar.

Error occurred in updateEffectsList().
2017-04-24 08:25:46: ********
2017-04-24 08:26:36: 08:26:36 finalcutpr:     Reloading Final Cut Pro Preferences: 1492993496; 1492993595
2017-04-24 08:34:52: 08:34:52                 Reloading Final Cut Pro Preferences: 1492993595; 1492994091
2017-04-24 08:34:53: ********
2017-04-24 08:34:53: 08:34:53 ERROR:    dialog: Unable to activate the Effects sidebar.

Error occurred in updateEffectsList().
2017-04-24 08:34:53: ********
2017-04-24 08:36:16: ********
2017-04-24 08:36:16: 08:36:16 ERROR:    dialog: Unable to activate the Effects sidebar.

Error occurred in updateEffectsList().
2017-04-24 08:36:16: ********
2017-04-24 08:36:29: 08:36:29 finalcutpr:     Reloading Final Cut Pro Preferences: 1492994091; 1492994189
```

**Comment by latenitefilms** [comment]
FYI:

```
CommandPost v1.0.0-beta.3

macOS Version:                  10.12.4
CommandPost Locale:             en
Current Keyboard Layout:        U.S.
Final Cut Pro Path:             /Applications/Final Cut Pro/Final Cut Pro 10-3-2.app/
Final Cut Pro Version:          10.3.2
Final Cut Pro Language:         en
Developer Mode:                 false

2017-04-25 00:57:42: 2017-04-25 00:57:42: -- Loading /Users/latenitechris/Documents/Github/CommandPost/src/extensions/cp/init.lua
2017-04-25 00:57:42: -- Loading extension: uielement
2017-04-25 00:57:42: -- Loading extension: window
2017-04-25 00:57:42: 00:57:42    menubar:     Loaded menu map from '/Users/latenitechris/Documents/Github/CommandPost/src/extensions/cp/apple/finalcutpro/menumap.json'
2017-04-25 00:57:42:                  cp:     Loading Plugins:
2017-04-25 00:57:43: -- Loading extension: inspect
2017-04-25 00:57:43: ------
2017-04-25 00:57:43: Panel ID: accessibility
2017-04-25 00:57:43: Panel Enabled: false
2017-04-25 00:57:43: ------
2017-04-25 00:57:43: Panel ID: complete
2017-04-25 00:57:43: Panel Enabled: unspecified
2017-04-25 00:57:43: ------
2017-04-25 00:57:43: Panel ID: intro
2017-04-25 00:57:43: Panel Enabled: true
2017-04-25 00:57:43: ------
2017-04-25 00:57:43: Panel ID: appmissing
2017-04-25 00:57:43: Panel Enabled: false
2017-04-25 00:57:43: ------
2017-04-25 00:57:43: Panel ID: commandset
2017-04-25 00:57:43: Panel Enabled: true
2017-04-25 00:57:43: ------
2017-04-25 00:57:43: Panel ID: scanfinalcutpro
2017-04-25 00:57:43: Panel Enabled: true
2017-04-25 00:57:43: ------
2017-04-25 00:57:44: -- Done.
2017-04-25 00:58:12: ********
2017-04-25 00:58:12: 00:58:12 ERROR:   LuaSkin: hs.webview.usercontent callback error: ...extensions/cp/apple/finalcutpro/main/TimelineToolbar.lua:117: attempt to index a nil value
stack traceback:
	...extensions/cp/apple/finalcutpro/main/TimelineToolbar.lua:117: in function <...extensions/cp/apple/finalcutpro/main/TimelineToolbar.lua:116>
	(...tail calls...)
	...mandPost/src/extensions/cp/apple/finalcutpro/axutils.lua:164: in function 'cp.apple.finalcutpro.axutils.cache'
	(...tail calls...)
	...t/src/extensions/cp/apple/finalcutpro/ui/RadioButton.lua:59: in function 'cp.apple.finalcutpro.ui.RadioButton.isChecked'
	(...tail calls...)
	.../extensions/cp/apple/finalcutpro/main/EffectsBrowser.lua:311: in function 'cp.apple.finalcutpro.main.EffectsBrowser.saveLayout'
	...CommandPost/src/plugins/finalcutpro/timeline/effects.lua:415: in field 'updateEffectsList'
	.../src/plugins/finalcutpro/preferences/scanfinalcutpro.lua:82: in field 'scanFinalCutPro'
	...gins/finalcutpro/welcome/panels/scanfinalcutpro/init.lua:41: in field 'callbackFn'
	...ub/CommandPost/src/plugins/core/welcome/manager/init.lua:215: in function <...ub/CommandPost/src/plugins/core/welcome/manager/init.lua:209>
2017-04-25 00:58:12: ********

```

**Comment by latenitefilms** [comment]
FYI - Scanning Final Cut Pro seems to fail if there's no Library open.

**Comment by latenitefilms** [comment]
Michael Stathopoulos [says](https://www.facebook.com/groups/commandpost/permalink/1854897918099244/):

> Every time I try to scan FCPX it stops after scanning effects. No transitions, titles, or generators.

**Comment by randomeizer** [comment]
I fixed an issue related to this for the Generators Browser, in #542. I'll check out the specific issues in the stack traces as well though - they seem a little different.

**Comment by latenitefilms** [comment]
Even with the latest `develop`, I'm still having issues with scanning generators when doing a fresh install of CommandPost. It doesn't work the first time for whatever reason, but seems to work fine the second time. Sadly no helpful error messages, so we'll just need to do some more testing.

**Comment by latenitefilms** [comment]
Hopefully this will be addressed in #667.
